# Generated by Django 4.2.3 on 2023-07-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateField()),
                ('numero_chamado', models.CharField(max_length=50)),
                ('problema_relatado', models.TextField()),
                ('resolucao', models.TextField()),
                ('data_solucao', models.DateField()),
                ('tipo_atendimento', models.CharField(choices=[('Comercial', 'Comercial'), ('Sobreaviso', 'Sobreaviso')], max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ChamadoAtendido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_chamado', models.CharField(max_length=50)),
                ('problema_relatado', models.TextField()),
                ('resolucao', models.TextField()),
                ('data_solucao', models.DateField()),
                ('tipo_atendimento', models.CharField(choices=[('Comercial', 'Comercial'), ('Sobreaviso', 'Sobreaviso')], max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
            ],
        ),
    ]
